name: uno_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Sticking with 3.10 for compatibility
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - tensorflow  # Let conda find a compatible version
  - h5py
  - matplotlib
  - pyyaml
  - tqdm
  - fastparquet
  - pyarrow
