name: uno_env
channels:
  - conda-forge  # Prioritize conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy  # Let conda-forge choose
  - pandas  # Let conda-forge choose
  - scipy  # Let conda-forge choose
  - scikit-learn  # Let conda-forge choose
  - tensorflow  # Let conda-forge choose
  - h5py  # Let conda-forge choose
  - matplotlib  # Let conda-forge choose
  - pyyaml  # Let conda-forge choose
  - tqdm  # Let conda-forge choose
  - fastparquet  # Let conda-forge choose
  - pyarrow  # Let conda-forge choose
  - pip:
    - improvelib
